name: resus_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.54+6

environment:
  sdk: ">=3.0.0 < 4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.4
  http:
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.2
  url_launcher: ^6.1.12
  dropdown_button2: ^2.1.3
  flutter_dash: ^1.0.0
  file_picker: ^8.0.3
  mime: ^1.0.4
  floor: ^1.4.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  percent_indicator: ^4.2.3
  image_picker: ^1.0.4
  recase: ^4.1.0
  custom_searchable_dropdown: ^2.1.1
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  cron: ^0.6.1
  dio: ^5.2.1+1
  device_preview:
  sizer: ^2.0.15
  webview_flutter: ^3.0.0
  flutter_image_compress: ^2.0.3
  flutter_local_notifications: ^17.1.2
  badges: ^3.1.1
  flutter_background_service: ^5.0.5
  device_info_plus:
  intl:
  android_intent_plus: ^5.0.2
  sentry_flutter: ^7.15.0
  root: ^2.0.3
  package_info_plus: ^4.0.2
  external_app_launcher: ^4.0.0
  pin_code_fields: ^8.0.1
  toggle_switch: ^2.1.0
  flutter_date_range_picker: ^0.1.1
  flutter_lints:
  flutter_inappwebview: ^5.7.2+3
  flutter_pdfview: ^1.3.1
  flutter_svg: ^2.0.10+1
  d_chart: ^2.6.9
  open_filex: ^4.4.0
  syncfusion_flutter_xlsio: ^25.2.6
  path_provider: ^2.1.2
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/languages/
    - assets/images/1.5x/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/images/4.0x/

  fonts:
    - family: Font1
      fonts:
        - asset: assets/fonts/Barlow-Light.ttf
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.ttf
    - family: ARIAL
      fonts:
        - asset: assets/fonts/ARIAL.ttf
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf

        - asset: assets/fonts/NunitoSans-Regular.ttf

        - asset: assets/fonts/NunitoSans-SemiBold.ttf

        - asset: assets/fonts/NunitoSans-Bold.ttf

    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf